### PR TITLE
Update to 6.x

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
On OSX:
```
ERROR: Feature "webengine_system_icu": Forcing to "ON" breaks its condition:
    ICU_FOUND
Condition values dump:
    ICU_FOUND = ""

ERROR: Feature "webengine_system_ffmpeg": Forcing to "ON" breaks its condition:
    FFMPEG_FOUND AND QT_FEATURE_webengine_system_opus AND QT_FEATURE_webengine_system_libwebp
Condition values dump:
    FFMPEG_FOUND = ""
    QT_FEATURE_webengine_system_opus = "OFF"
    QT_FEATURE_webengine_system_libwebp = "OFF"

ERROR: Feature "webengine_system_libevent": Forcing to "ON" breaks its condition:
    UNIX AND LIBEVENT_FOUND
Condition values dump:
    UNIX = "1"
    LIBEVENT_FOUND = ""
```

**Comment by h-vetinari** [comment]
Also not building correctly on linux:
```
// Path to a library.
pkgcfg_lib_ZLIB_z:FILEPATH=$PREFIX/lib/libz.so

[1/2] Check QtWebEngine support
QtWebEngine will not be built: Could not find all necessary libraries for qpa-xcb support. X11:YES LIBDRM:YES XCOMPOSITE:NO XCURSOR:NO XRANDR:NO XI:NO XPROTO:NO XSHMFENCE:NO XTST:NO
[1/2] Install the project...
-- Install configuration: "Release"
-- Up-to-date: $PREFIX/lib/cmake/Qt6
-- Installing: $PREFIX/lib/cmake/Qt6/FindSnappy.cmake
-- Installing: $PREFIX/lib/cmake/Qt6/FindGPerf.cmake
-- Installing: $PREFIX/lib/cmake/Qt6/FindGn.cmake
-- Installing: $PREFIX/lib/cmake/Qt6/FindPkgConfigHost.cmake
-- Installing: $PREFIX/lib/cmake/Qt6/FindNodejs.cmake
-- Installing: $PREFIX/lib/cmake/Qt6/FindNinja.cmake

Resource usage statistics from building qt6-webengine:
   Process count: 7
   CPU time: Sys=0:00:06.6, User=0:00:00.8
   Memory: 74.7M
   Disk usage: 3.1M
   Time elapsed: 0:00:21.5
```

**Comment by h-vetinari** [comment]
And finally windows:
```
ERROR: Feature "webengine_system_icu": Forcing to "ON" breaks its condition:
    ICU_FOUND
Condition values dump:
    ICU_FOUND = ""

ERROR: Feature "webengine_system_libevent": Forcing to "ON" breaks its condition:
    UNIX AND LIBEVENT_FOUND
Condition values dump:
    UNIX = ""
    LIBEVENT_FOUND = ""
```

**Comment by jschueller** [comment]
giving up on this...

**Pull request closed without merging**
