### PR TITLE
5.15.13

### PR DESCRIPTION
**Pull request by adrianinsaval**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
I've got builds for osx_644 and linux_64: https://anaconda.org/freecad/qt-webengine/files

still can't figure out how to get a build for osx_arm64, trying to build linux_aarch64 crosscompiled from x86_64

Is it possible to increase the timeout for the ci? maybe it'll work without needing more intervention

**Comment by adrianinsaval** [comment]
builds for the 5 platforms, what's the next step @hmaarrfk

**Comment by hmaarrfk** [comment]
> trying to build linux_aarch64 crosscompiled from x86_64

this is what i do too.

> Is it possible to increase the timeout for the ci? maybe it'll work without needing more intervention

We have some other big machine CIs, but I don't think it will be enough for this. I'm not very good at using them, and to me they are still rather experimental.

> builds for the 5 platforms, what's the next step @hmaarrfk

Did you happen to save the log files?
We would technically need to follow: https://github.com/conda-forge/cfep/blob/main/cfep-03.md

I can help on the linux builds, but windows and OSX i don't have access to machines that can do that.

**Comment by hmaarrfk** [comment]
I also somewhat want to get:

https://github.com/conda-forge/qt-main-feedstock/pull/245
https://github.com/conda-forge/qt-main-feedstock/pull/244

mereged in before the 5.15 upgrade since it seems that it will unblock the mysql pin or i guess we can do the 5.15.13 pin along with the mysql upgrade if you want to merge in my changes. No need to merge in the rerenders

**Comment by hmaarrfk** [comment]
Ok this is really awesome work. I think the way to go will be:

1. [ ] I will create a branch for 5.15.8 on qt-main just to have a reference point for migrations in case of any delays.
2. [ ] I would like to pin qt-main to 5.15.8 at build time to help downstream packages be compatible with both while we build everything out. https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5670
1. [ ] Rebase or merge from conda-forge/main your 5.15.13 branch to take in the new changes for mysql 13 and pulseaudio-client 17
2. [ ] Get 5.15.13 uploaded to conda-forge https://github.com/conda-forge/cfep/blob/main/cfep-03.md Generally we ask for logs.
4. [ ] Get webengine 5.15.13 uploaded to conda-forge.
5. [ ] Create "qt" 5.15.13 at https://github.com/conda-forge/qt-feedstock

**Comment by h-vetinari** [comment]
Any updates on this effort here? 🙃 

I _think_ it's gonna be necessary to unblock pyside2 for py312, which is the migration I'm looking at right now.

**Comment by adrianinsaval** [comment]
> Any updates on this effort here? 🙃
> 
> I _think_ it's gonna be necessary to unblock pyside2 for py312, which is the migration I'm looking at right now.

if you're still interested on this: https://github.com/conda-forge/pyside2-feedstock/pull/250

**Pull request closed without merging**
