### PR TITLE
5.15.15

### PR DESCRIPTION
**Pull request by adrianinsaval**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
some packages available at https://anaconda.org/freecad/qt-webengine/files and their logs: 
[qt-webengine-5.15.15-logs.tar.gz](https://github.com/user-attachments/files/17493949/qt-webengine-5.15.15-logs.tar.gz)

I'm building windows on my machine now. I haven't succeeded in building for aarch64 yet, it randomly gets killed with no info about why in the output at ~17000/25000 and I haven't managed to crosscompile yet

**Comment by adrianinsaval** [comment]
is there anyone available that can make an aarch64 build?

**Comment by adrianinsaval** [comment]
windows build now also available, log: [qt-webengine-5.15.15-win_64_.tar.gz](https://github.com/user-attachments/files/17500744/qt-webengine-5.15.15-win_64_.tar.gz)

**Comment by hmaarrfk** [comment]
do you have the ability to build OSX?

**Comment by hmaarrfk** [comment]
I don't want to pull the qt-main package from your channel. Lets get https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5670 merged first.

**Comment by adrianinsaval** [comment]
> do you have the ability to build OSX?

yes it's already built

**Comment by hmaarrfk** [comment]
great. lets get qt-main merged in then start to shift our focus here. slowly.

**Comment by adrianinsaval** [comment]
I had already built packages with my previous qt-main builds, do I need to rebuild?

**Comment by adrianinsaval** [comment]
I can't get aarch64 to build, I've tried 3 different pcs (linux x86, mac x86, mac arm) now and they all just stop at some point with no error message, I know for a fact that the build can get past that point though since it almost finished building in cirrus ci but times out https://cirrus-ci.com/task/6589490976784384
I've got no clue what's different on my machines.

**Comment by adrianinsaval** [comment]
> I had already built packages with my previous qt-main builds, do I need to rebuild?

I've rebuilt the packages just in case, here are the logs: 
[qt-webengine-5.15.15-build-logs.tar.gz](https://github.com/user-attachments/files/17534145/qt-webengine-5.15.15-build-logs.tar.gz)

they have cfep03 label

**Comment by hmaarrfk** [comment]
part of the prolem with your builds is that they include a package from the `freecad` 

I know this is pedantic to worry about, but the fear is that it becomes more than "1" package

Anyway, its fine since I know you were working on things in parallel, but in the future (hopefully there won't be many) it would be nice to just wait before triggering the builds meant for conda-forge.

sometimes it just means uploading to a different channel.

just so that it is noted, the build number 1 because the one building CFEP03 already had build 0 on their channel. This is OK by me.

**Comment by hmaarrfk** [comment]
Thanks you so much for your help!

**Comment by h-vetinari** [comment]
Should we try to use https://github.com/Quansight/open-gpu-server/ for the linux builds? That way we could at least build aarch in CI (would require cross-compilation though).

Not sure if I understood correctly, but AFAIU we don't have aarch builds for 5.15.15 yet, right?

**Comment by hmaarrfk** [comment]
correct, there are no aarch builds

you can try the large runners, the osx and windows builds hurt me more....

**Comment by adrianinsaval** [comment]
> Should we try to use https://github.com/Quansight/open-gpu-server/ for the linux builds? That way we could at least build aarch in CI (would require cross-compilation though).
> 
> Not sure if I understood correctly, but AFAIU we don't have aarch builds for 5.15.15 yet, right?

I have not succeeded in cross compiling so far, you would need to investigate more and do more patching for that.

I'm now trying to run conda-build manually in an emulated linux-anvil-aarch64 podman container. It's been running since yesterday and it's at 23595/25026 now.

**Comment by hmaarrfk** [comment]
cross compiling in qt 5.15 is really hard.

Qemu + 24h + compilation time "is standard".

Honestly, I didn't realize that aarch64 builds were missing, and I shouldn't have clicked "merge" without at least acknowledging it.

keep me posted on the progress.

**Comment by adrianinsaval** [comment]
aarch64 build is now available in cfep03 label, here is the log: 
[log.tar.gz](https://github.com/user-attachments/files/17554686/log.tar.gz)

**Comment by hmaarrfk** [comment]
thx uploaded

**Pull request merged**
